### ISSUE TITLE
Upload script crashes on non-directory input

### ISSUE THREAD

**Issue by jlumbroso** [PrincetonUniversity/codePost-tools#2]
The following fatal error occurred when the script was provided a set of submissions, one of which was a file instead of a folder:
```
Processing ./alt.push.err.txt
[INFO] Submission: alt.push.err.txt for students ['alt.push.err.txt']
Traceback (most recent call last):
  File "/u/cos226/.local/bin/push-to-codePost", line 447, in <module>
    if uploadFolderByNetID(s, without_tests=params['without_tests']):
  File "/u/cos226/.local/bin/push-to-codePost", line 289, in uploadFolderByNetID
    files = listFiles(path, fullPaths=True)
  File "/u/cos226/.local/bin/push-to-codePost", line 160, in listFiles
    return [os.path.join(path, f) for f in os.listdir(path) if os.path.isfile(os.path.join(path, f))]
NotADirectoryError: [Errno 20] Not a directory: './alt.push.err.txt'
```

**Comment by jlumbroso** [comment]
Fixed by  6455a7677427c2415a3a5825f9e24b4cdb8bafac
